"""
ingest/mock_fetcher.py
─────────────────────
PURPOSE: Fetch raw social media posts.
In a real project this calls Reddit API (PRAW) or NewsAPI.
Here we generate realistic mock data so the whole pipeline works
without needing API keys.

WHAT YOU ALREADY KNOW: This is like loading a CSV in Colab.
The output is just a list of dictionaries — same as reading rows from a file.
"""

import random
from datetime import datetime, timedelta

# ── Realistic sample posts per topic ──────────────────────────────────────────

SAMPLE_POSTS = {
    "AI & Technology": [
        "ChatGPT is genuinely changing how I work every single day. Incredible tool.",
        "These AI companies are just hype machines. Nothing they ship actually works reliably.",
        "Just tried the new Claude model. The reasoning is surprisingly good for complex tasks.",
        "AI will replace half the jobs in the next decade. People are not ready for this.",
        "Machine learning models are getting cheaper to run. Great for small startups.",
        "The AI bubble is going to burst soon. Too much investment, too little real revenue.",
        "Open source LLMs are catching up fast to GPT-4. Exciting times for developers.",
        "Deepfakes generated by AI are becoming a serious threat to democracy.",
        "Neural networks explained well for once. This tutorial finally made it click for me.",
        "AI regulation is desperately needed before this gets completely out of hand.",
        "My productivity doubled after integrating AI tools into my daily workflow.",
        "Another day, another AI startup claiming to solve everything with transformers.",
        "The new image generation models produce absolutely stunning results.",
        "I'm frustrated with how unreliable AI coding assistants still are in production.",
        "Transfer learning has completely changed what's possible with small datasets.",
    ],
    "Stock Market": [
        "The market is looking bullish this week. Tech stocks are rallying hard.",
        "Interest rates are killing growth stocks. My portfolio is down 20% this month.",
        "Bought more index funds today. Long term patience always wins.",
        "Inflation data came in worse than expected. Expect more volatility ahead.",
        "Tesla earnings beat expectations. Stock up 8% after hours.",
        "The Fed's decision today completely tanked my options positions.",
        "Diversification is the only free lunch in investing. Never forget that.",
        "Crypto is crashing again. Same story every cycle, yet people never learn.",
        "Strong GDP growth report signals the economy is more resilient than feared.",
        "Banking sector looking shaky after those earnings misses last quarter.",
        "The IPO market is completely frozen. Nobody wants risk right now.",
        "Commodities are surging. Oil and gold both at multi-year highs.",
        "Small cap stocks finally showing signs of life after months of underperformance.",
        "Recession fears are overblown. Employment numbers remain extremely strong.",
        "My retirement account is up 30% this year. Bull markets are beautiful.",
    ],
    "Climate & Environment": [
        "Solar panel costs have dropped 90% in a decade. The energy transition is real.",
        "Another record-breaking heatwave. Climate change is not a future problem anymore.",
        "Electric vehicle adoption is accelerating faster than anyone predicted.",
        "The Amazon deforestation rates this year are absolutely devastating.",
        "Wind energy is now cheaper than coal in most of the world. Massive milestone.",
        "Climate summit produced more empty promises. We need action, not speeches.",
        "Carbon capture technology is finally becoming economically viable.",
        "Coral reef bleaching is occurring at unprecedented rates. We're losing them.",
        "Battery storage technology breakthrough could solve the intermittency problem.",
        "Plastic pollution in the ocean has reached catastrophic levels.",
        "Governments are finally starting to price carbon properly. Progress at last.",
        "Wildfires this season are the worst in recorded history. Terrifying.",
        "Green hydrogen is going to transform heavy industry and shipping.",
        "Biodiversity loss is accelerating even faster than climate change.",
        "Offshore wind farms are getting much more efficient and cost-effective.",
    ],
    "Sports": [
        "That last minute goal was absolutely incredible. Best match of the season!",
        "The referee made three terrible calls tonight. Completely ruined the game.",
        "New signing looks fantastic in training. Can't wait for the season opener.",
        "Our team's defense is a complete disaster. Same problems as last year.",
        "Championship game was the most exciting sporting event I've seen in years.",
        "Star player picked up an injury. Season could be over before it really began.",
        "The coach's tactical changes in the second half were absolutely brilliant.",
        "Home stadium atmosphere was electric last night. Fans were absolutely unreal.",
        "Transfer window was very disappointing. The board has no real ambition.",
        "Young talent emerging this season is genuinely exciting to watch develop.",
        "Controversial VAR decision cost us the match. The technology needs fixing.",
        "Record-breaking performance today. Witnessing sporting history live.",
        "Pre-season training looks intense. Team looks fitter than they've been in years.",
        "Lost again to a rival. Management needs to make changes immediately.",
        "Incredible comeback from 3 goals down. Never give up on this team.",
    ],
    "Health & Wellness": [
        "30 days of daily meditation and my anxiety is genuinely at an all-time low.",
        "Healthcare costs are absolutely impossible for middle-income families right now.",
        "New cancer treatment showing remarkable results in phase 3 clinical trials.",
        "Mental health crisis among young people is getting worse, not better.",
        "Plant-based diet completely transformed my energy levels and sleep quality.",
        "Gym membership prices are outrageous. Fitness should not be a luxury.",
        "New study confirms sleep is even more critical to health than we thought.",
        "Universal healthcare would solve so many of these systemic problems.",
        "Running a 5k for the first time. Fitness journey has been life-changing.",
        "Antibiotic resistance is a ticking time bomb that nobody is taking seriously.",
        "Intermittent fasting genuinely works for weight management. Research backs it up.",
        "Mental health stigma is finally starting to decrease. Still so much work to do.",
        "New Alzheimer's drug trial results look very promising. Cautious optimism.",
        "Processed food industry is deliberately addictive. It's a public health crisis.",
        "Yoga and strength training combination is unbeatable for overall wellbeing.",
    ],
}

SOURCES = ["Reddit", "Twitter/X", "NewsAPI", "HackerNews"]
AUTHORS = [
    "user_alpha", "techguru99", "market_watcher", "climate_hawk",
    "sports_fan_42", "health_enthusiast", "data_nerd", "news_junkie",
    "random_poster", "daily_commenter", "lurker_2024", "active_user",
    "opinion_sharer", "fact_checker_pro", "morning_reader",
]


def fetch_posts(topic: str = None, count: int = 80) -> list[dict]:
    """
    Simulates fetching posts from a social media API.

    Parameters:
        topic : Filter to a specific topic, or None for all topics
        count : How many posts to return

    Returns:
        List of dicts — each dict is one post with all its metadata.
        This is the same shape of data you'd get from the real Reddit API.

    ML ANALOGY: This is your data loading step — like pd.read_csv() in Colab.
    """
    topics = [topic] if topic else list(SAMPLE_POSTS.keys())
    posts = []

    # Generate posts going back 7 days so we have a time dimension to chart
    now = datetime.now()

    for _ in range(count):
        chosen_topic = random.choice(topics)
        text = random.choice(SAMPLE_POSTS[chosen_topic])

        # Add slight variation so not every post is identical
        variations = ["", " Thoughts?", " Discuss.", " What do you think?", ""]
        text = text + random.choice(variations)

        # Random timestamp within the last 7 days
        hours_ago = random.uniform(0, 168)  # 168 hours = 7 days
        timestamp = now - timedelta(hours=hours_ago)

        posts.append({
            "id":         f"post_{random.randint(100000, 999999)}",
            "text":       text,
            "author":     random.choice(AUTHORS),
            "source":     random.choice(SOURCES),
            "topic":      chosen_topic,
            "created_at": timestamp.isoformat(),
            "upvotes":    random.randint(0, 2400),
            "comments":   random.randint(0, 340),
        })

    return posts


if __name__ == "__main__":
    # Quick test — run this file directly to see sample output
    posts = fetch_posts(count=5)
    for p in posts:
        print(f"[{p['topic']}] {p['text'][:60]}...")
    print(f"\nTotal fetched: {len(fetch_posts())} posts")